// Generated by CoffeeScript 1.6.2
$(document).ready(function() {
  marked.setOptions({
    renderer: new marked.Renderer(),
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    sanitize: true,
    smartLists: true,
    smartypants: false
  });
  var text = marked($('.markdown').html());
  console.log(text);
  // $('.markdown').html(text);
  
  return $('.markdown-container').fadeIn({
    start: function() {
      return $("h1").fitText();
    }
  });
});
